### ISSUE TITLE
Any tips on how to pass data to widget?

### ISSUE THREAD

**Issue by corepay** [DJanoskova/Vuidget#3]
This is exactly what I have been looking for.  Have to have a remote server use my app.  Spent last few days struggling with iFrame and nuxt and postMessage yada yada without much progress.

So what is your suggestion to pass data back and forth to the widget?  My app has an api to external services and I need to have the host app pass on some params.  Ideally I should be able to return params to update their system as well.  Any advice or pointers?

**Comment by corepay** [comment]
figuring it out...

**Comment by Tusko** [comment]
Any news?
Mb 'data-' props?
